import OutcastsMathLab.Research.DeterministicFailure

/-! Generated by `Research/DeterministicFailure/gen_certificates.py`. Do not edit by hand.
Finite negative certificates: the two primes below have no Dahan witness at any pair of the
53-pair box used in the Outcasts failure atlas. Known criterion, not a new existence result. -/

namespace OutcastsMathLab.Research.HardPrimes20261005

open OutcastsMathLab.Research.DeterministicFailure

/-- The 53 pairs `(a, u)`: coprime `a, u ≤ 6`, and `u ∈ {11, 13, 17, 19, 23}`, `a ≤ 6`. -/
def box53 : List (ℕ × ℕ) := [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 1), (2, 3), (2, 5), (3, 1), (3, 2), (3, 4), (3, 5), (4, 1), (4, 3), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4), (5, 6), (6, 1), (6, 5), (1, 11), (2, 11), (3, 11), (4, 11), (5, 11), (6, 11), (1, 13), (2, 13), (3, 13), (4, 13), (5, 13), (6, 13), (1, 17), (2, 17), (3, 17), (4, 17), (5, 17), (6, 17), (1, 19), (2, 19), (3, 19), (4, 19), (5, 19), (6, 19), (1, 23), (2, 23), (3, 23), (4, 23), (5, 23), (6, 23)]

theorem p345601_a1_u1 : ∀ s, ¬ DivisorWitness 345601 1 1 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (172801, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u2 : ∀ s, ¬ DivisorWitness 345601 1 2 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (115201, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u3 : ∀ s, ¬ DivisorWitness 345601 1 3 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (7, 1), (12343, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u4 : ∀ s, ¬ DivisorWitness 345601 1 4 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (13, 2), (409, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u5 : ∀ s, ¬ DivisorWitness 345601 1 5 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 1), (57601, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u6 : ∀ s, ¬ DivisorWitness 345601 1 6 s :=
  no_divisorWitness_of_cert (L := [(345607, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u1 : ∀ s, ¬ DivisorWitness 345601 2 1 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (17, 1), (13553, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u3 : ∀ s, ¬ DivisorWitness 345601 2 3 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (138241, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u5 : ∀ s, ¬ DivisorWitness 345601 2 5 s :=
  no_divisorWitness_of_cert (L := [(11, 1), (31, 1), (2027, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u1 : ∀ s, ¬ DivisorWitness 345601 3 1 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (259201, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u2 : ∀ s, ¬ DivisorWitness 345601 3 2 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (7, 1), (11, 1), (2693, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u4 : ∀ s, ¬ DivisorWitness 345601 3 4 s :=
  no_divisorWitness_of_cert (L := [(59, 1), (17573, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u5 : ∀ s, ¬ DivisorWitness 345601 3 5 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (29, 1), (41, 1), (109, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u1 : ∀ s, ¬ DivisorWitness 345601 4 1 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (151, 1), (1831, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u3 : ∀ s, ¬ DivisorWitness 345601 4 3 s :=
  no_divisorWitness_of_cert (L := [(13, 1), (43, 1), (2473, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u5 : ∀ s, ¬ DivisorWitness 345601 4 5 s :=
  no_divisorWitness_of_cert (L := [(3, 2), (7, 1), (21943, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u1 : ∀ s, ¬ DivisorWitness 345601 5 1 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 1), (7, 1), (41143, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u2 : ∀ s, ¬ DivisorWitness 345601 5 2 s :=
  no_divisorWitness_of_cert (L := [(181, 1), (9547, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u3 : ∀ s, ¬ DivisorWitness 345601 5 3 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (61, 1), (3541, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u4 : ∀ s, ¬ DivisorWitness 345601 5 4 s :=
  no_divisorWitness_of_cert (L := [(3, 2), (101, 1), (1901, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u6 : ∀ s, ¬ DivisorWitness 345601 5 6 s :=
  no_divisorWitness_of_cert (L := [(37, 1), (46703, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u1 : ∀ s, ¬ DivisorWitness 345601 6 1 s :=
  no_divisorWitness_of_cert (L := [(2073607, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u5 : ∀ s, ¬ DivisorWitness 345601 6 5 s :=
  no_divisorWitness_of_cert (L := [(23, 1), (89, 1), (1013, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u11 : ∀ s, ¬ DivisorWitness 345601 1 11 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (3, 1), (83, 1), (347, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u11 : ∀ s, ¬ DivisorWitness 345601 2 11 s :=
  no_divisorWitness_of_cert (L := [(167, 1), (4139, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u11 : ∀ s, ¬ DivisorWitness 345601 3 11 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (37, 1), (14011, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u11 : ∀ s, ¬ DivisorWitness 345601 4 11 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (5, 1), (23, 1), (4007, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u11 : ∀ s, ¬ DivisorWitness 345601 5 11 s :=
  no_divisorWitness_of_cert (L := [(2, 4), (17, 1), (6353, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u11 : ∀ s, ¬ DivisorWitness 345601 6 11 s :=
  no_divisorWitness_of_cert (L := [(7, 1), (13, 1), (22787, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u13 : ∀ s, ¬ DivisorWitness 345601 1 13 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (172807, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u13 : ∀ s, ¬ DivisorWitness 345601 2 13 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (5, 1), (7, 1), (29, 1), (227, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u13 : ∀ s, ¬ DivisorWitness 345601 3 13 s :=
  no_divisorWitness_of_cert (L := [(2, 4), (11, 1), (43, 1), (137, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u13 : ∀ s, ¬ DivisorWitness 345601 4 13 s :=
  no_divisorWitness_of_cert (L := [(179, 1), (7723, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u13 : ∀ s, ¬ DivisorWitness 345601 5 13 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 2), (96001, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u13 : ∀ s, ¬ DivisorWitness 345601 6 13 s :=
  no_divisorWitness_of_cert (L := [(2073619, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u17 : ∀ s, ¬ DivisorWitness 345601 1 17 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 2), (7, 1), (13, 1), (211, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u17 : ∀ s, ¬ DivisorWitness 345601 2 17 s :=
  no_divisorWitness_of_cert (L := [(23, 1), (41, 1), (733, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u17 : ∀ s, ¬ DivisorWitness 345601 3 17 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (5, 1), (47, 1), (1103, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u17 : ∀ s, ¬ DivisorWitness 345601 4 17 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (19, 1), (79, 1), (307, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u17 : ∀ s, ¬ DivisorWitness 345601 5 17 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (864011, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u17 : ∀ s, ¬ DivisorWitness 345601 6 17 s :=
  no_divisorWitness_of_cert (L := [(1051, 1), (1973, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u19 : ∀ s, ¬ DivisorWitness 345601 1 19 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (5, 1), (11, 1), (1571, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u19 : ∀ s, ¬ DivisorWitness 345601 2 19 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (113, 1), (2039, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u19 : ∀ s, ¬ DivisorWitness 345601 3 19 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (518411, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u19 : ∀ s, ¬ DivisorWitness 345601 4 19 s :=
  no_divisorWitness_of_cert (L := [(7, 1), (17, 1), (11617, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u19 : ∀ s, ¬ DivisorWitness 345601 5 19 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (3, 1), (89, 1), (809, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u19 : ∀ s, ¬ DivisorWitness 345601 6 19 s :=
  no_divisorWitness_of_cert (L := [(5, 3), (53, 1), (313, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a1_u23 : ∀ s, ¬ DivisorWitness 345601 1 23 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (3, 1), (14401, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a2_u23 : ∀ s, ¬ DivisorWitness 345601 2 23 s :=
  no_divisorWitness_of_cert (L := [(5, 2), (43, 1), (643, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a3_u23 : ∀ s, ¬ DivisorWitness 345601 3 23 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (7, 1), (31, 1), (2389, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a4_u23 : ∀ s, ¬ DivisorWitness 345601 4 23 s :=
  no_divisorWitness_of_cert (L := [(3, 5), (5689, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a5_u23 : ∀ s, ¬ DivisorWitness 345601 5 23 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (432007, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p345601_a6_u23 : ∀ s, ¬ DivisorWitness 345601 6 23 s :=
  no_divisorWitness_of_cert (L := [(1163, 1), (1783, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

/-- `p = 345601` has no Dahan witness at any pair of the 53-pair box. -/
theorem no_witness_345601_box : ∀ au ∈ box53, ∀ s, ¬ DivisorWitness 345601 au.1 au.2 s := by
  intro au hau
  simp only [box53, List.mem_cons, List.not_mem_nil, or_false] at hau
  rcases hau with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact p345601_a1_u1
  · exact p345601_a1_u2
  · exact p345601_a1_u3
  · exact p345601_a1_u4
  · exact p345601_a1_u5
  · exact p345601_a1_u6
  · exact p345601_a2_u1
  · exact p345601_a2_u3
  · exact p345601_a2_u5
  · exact p345601_a3_u1
  · exact p345601_a3_u2
  · exact p345601_a3_u4
  · exact p345601_a3_u5
  · exact p345601_a4_u1
  · exact p345601_a4_u3
  · exact p345601_a4_u5
  · exact p345601_a5_u1
  · exact p345601_a5_u2
  · exact p345601_a5_u3
  · exact p345601_a5_u4
  · exact p345601_a5_u6
  · exact p345601_a6_u1
  · exact p345601_a6_u5
  · exact p345601_a1_u11
  · exact p345601_a2_u11
  · exact p345601_a3_u11
  · exact p345601_a4_u11
  · exact p345601_a5_u11
  · exact p345601_a6_u11
  · exact p345601_a1_u13
  · exact p345601_a2_u13
  · exact p345601_a3_u13
  · exact p345601_a4_u13
  · exact p345601_a5_u13
  · exact p345601_a6_u13
  · exact p345601_a1_u17
  · exact p345601_a2_u17
  · exact p345601_a3_u17
  · exact p345601_a4_u17
  · exact p345601_a5_u17
  · exact p345601_a6_u17
  · exact p345601_a1_u19
  · exact p345601_a2_u19
  · exact p345601_a3_u19
  · exact p345601_a4_u19
  · exact p345601_a5_u19
  · exact p345601_a6_u19
  · exact p345601_a1_u23
  · exact p345601_a2_u23
  · exact p345601_a3_u23
  · exact p345601_a4_u23
  · exact p345601_a5_u23
  · exact p345601_a6_u23

#print axioms no_witness_345601_box

theorem p670849_a1_u1 : ∀ s, ¬ DivisorWitness 670849 1 1 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (5, 2), (13417, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u2 : ∀ s, ¬ DivisorWitness 670849 1 2 s :=
  no_divisorWitness_of_cert (L := [(3, 2), (131, 1), (569, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u3 : ∀ s, ¬ DivisorWitness 670849 1 3 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (7, 1), (13, 1), (19, 1), (97, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u4 : ∀ s, ¬ DivisorWitness 670849 1 4 s :=
  no_divisorWitness_of_cert (L := [(670853, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u5 : ∀ s, ¬ DivisorWitness 670849 1 5 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 1), (17, 1), (6577, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u6 : ∀ s, ¬ DivisorWitness 670849 1 6 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (134171, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u1 : ∀ s, ¬ DivisorWitness 670849 2 1 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (447233, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u3 : ∀ s, ¬ DivisorWitness 670849 2 3 s :=
  no_divisorWitness_of_cert (L := [(1341701, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u5 : ∀ s, ¬ DivisorWitness 670849 2 5 s :=
  no_divisorWitness_of_cert (L := [(11, 1), (283, 1), (431, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u1 : ∀ s, ¬ DivisorWitness 670849 3 1 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (503137, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u2 : ∀ s, ¬ DivisorWitness 670849 3 2 s :=
  no_divisorWitness_of_cert (L := [(7, 1), (11, 1), (59, 1), (443, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u4 : ∀ s, ¬ DivisorWitness 670849 3 4 s :=
  no_divisorWitness_of_cert (L := [(31, 1), (64921, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u5 : ∀ s, ¬ DivisorWitness 670849 3 5 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (197, 1), (1277, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u1 : ∀ s, ¬ DivisorWitness 670849 4 1 s :=
  no_divisorWitness_of_cert (L := [(2683397, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u3 : ∀ s, ¬ DivisorWitness 670849 4 3 s :=
  no_divisorWitness_of_cert (L := [(17, 1), (29, 1), (5443, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u5 : ∀ s, ¬ DivisorWitness 670849 4 5 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (7, 1), (127781, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u1 : ∀ s, ¬ DivisorWitness 670849 5 1 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 2), (7, 2), (3803, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u2 : ∀ s, ¬ DivisorWitness 670849 5 2 s :=
  no_divisorWitness_of_cert (L := [(13, 1), (258019, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u3 : ∀ s, ¬ DivisorWitness 670849 5 3 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (419281, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u4 : ∀ s, ¬ DivisorWitness 670849 5 4 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (47, 1), (23789, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u6 : ∀ s, ¬ DivisorWitness 670849 5 6 s :=
  no_divisorWitness_of_cert (L := [(23, 1), (41, 1), (3557, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u1 : ∀ s, ¬ DivisorWitness 670849 6 1 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (805019, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u5 : ∀ s, ¬ DivisorWitness 670849 6 5 s :=
  no_divisorWitness_of_cert (L := [(13, 1), (309623, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u11 : ∀ s, ¬ DivisorWitness 670849 1 11 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (3, 2), (5, 1), (3727, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u11 : ∀ s, ¬ DivisorWitness 670849 2 11 s :=
  no_divisorWitness_of_cert (L := [(47, 1), (28547, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u11 : ∀ s, ¬ DivisorWitness 670849 3 11 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (1006279, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u11 : ∀ s, ¬ DivisorWitness 670849 4 11 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (73, 1), (12253, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u11 : ∀ s, ¬ DivisorWitness 670849 5 11 s :=
  no_divisorWitness_of_cert (L := [(2, 4), (29, 1), (7229, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u11 : ∀ s, ¬ DivisorWitness 670849 6 11 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (7, 3), (2347, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u13 : ∀ s, ¬ DivisorWitness 670849 1 13 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (509, 1), (659, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u13 : ∀ s, ¬ DivisorWitness 670849 2 13 s :=
  no_divisorWitness_of_cert (L := [(3, 3), (7, 1), (31, 1), (229, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u13 : ∀ s, ¬ DivisorWitness 670849 3 13 s :=
  no_divisorWitness_of_cert (L := [(2, 4), (5, 1), (11, 1), (2287, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u13 : ∀ s, ¬ DivisorWitness 670849 4 13 s :=
  no_divisorWitness_of_cert (L := [(41, 1), (65449, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u13 : ∀ s, ¬ DivisorWitness 670849 5 13 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 1), (43, 1), (13001, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u13 : ∀ s, ¬ DivisorWitness 670849 6 13 s :=
  no_divisorWitness_of_cert (L := [(17, 1), (236771, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u17 : ∀ s, ¬ DivisorWitness 670849 1 17 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (3, 1), (7, 1), (15973, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u17 : ∀ s, ¬ DivisorWitness 670849 2 17 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (268343, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u17 : ∀ s, ¬ DivisorWitness 670849 3 17 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (337, 1), (1493, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u17 : ∀ s, ¬ DivisorWitness 670849 4 17 s :=
  no_divisorWitness_of_cert (L := [(3, 2), (298157, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u17 : ∀ s, ¬ DivisorWitness 670849 5 17 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (31, 1), (54101, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u17 : ∀ s, ¬ DivisorWitness 670849 6 17 s :=
  no_divisorWitness_of_cert (L := [(4025111, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u19 : ∀ s, ¬ DivisorWitness 670849 1 19 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (11, 1), (79, 1), (193, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u19 : ∀ s, ¬ DivisorWitness 670849 2 19 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (13, 1), (34403, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u19 : ∀ s, ¬ DivisorWitness 670849 3 19 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (71, 1), (14173, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u19 : ∀ s, ¬ DivisorWitness 670849 4 19 s :=
  no_divisorWitness_of_cert (L := [(5, 1), (7, 1), (43, 1), (1783, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u19 : ∀ s, ¬ DivisorWitness 670849 5 19 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (3, 3), (53, 1), (293, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u19 : ∀ s, ¬ DivisorWitness 670849 6 19 s :=
  no_divisorWitness_of_cert (L := [(29, 1), (138797, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a1_u23 : ∀ s, ¬ DivisorWitness 670849 1 23 s :=
  no_divisorWitness_of_cert (L := [(2, 3), (3, 1), (27953, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a2_u23 : ∀ s, ¬ DivisorWitness 670849 2 23 s :=
  no_divisorWitness_of_cert (L := [(271, 1), (4951, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a3_u23 : ∀ s, ¬ DivisorWitness 670849 3 23 s :=
  no_divisorWitness_of_cert (L := [(2, 1), (5, 1), (7, 1), (28751, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a4_u23 : ∀ s, ¬ DivisorWitness 670849 4 23 s :=
  no_divisorWitness_of_cert (L := [(3, 1), (137, 1), (6529, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a5_u23 : ∀ s, ¬ DivisorWitness 670849 5 23 s :=
  no_divisorWitness_of_cert (L := [(2, 2), (59, 1), (61, 1), (233, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

theorem p670849_a6_u23 : ∀ s, ¬ DivisorWitness 670849 6 23 s :=
  no_divisorWitness_of_cert (L := [(1187, 1), (3391, 1)])
    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)

/-- `p = 670849` has no Dahan witness at any pair of the 53-pair box. -/
theorem no_witness_670849_box : ∀ au ∈ box53, ∀ s, ¬ DivisorWitness 670849 au.1 au.2 s := by
  intro au hau
  simp only [box53, List.mem_cons, List.not_mem_nil, or_false] at hau
  rcases hau with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact p670849_a1_u1
  · exact p670849_a1_u2
  · exact p670849_a1_u3
  · exact p670849_a1_u4
  · exact p670849_a1_u5
  · exact p670849_a1_u6
  · exact p670849_a2_u1
  · exact p670849_a2_u3
  · exact p670849_a2_u5
  · exact p670849_a3_u1
  · exact p670849_a3_u2
  · exact p670849_a3_u4
  · exact p670849_a3_u5
  · exact p670849_a4_u1
  · exact p670849_a4_u3
  · exact p670849_a4_u5
  · exact p670849_a5_u1
  · exact p670849_a5_u2
  · exact p670849_a5_u3
  · exact p670849_a5_u4
  · exact p670849_a5_u6
  · exact p670849_a6_u1
  · exact p670849_a6_u5
  · exact p670849_a1_u11
  · exact p670849_a2_u11
  · exact p670849_a3_u11
  · exact p670849_a4_u11
  · exact p670849_a5_u11
  · exact p670849_a6_u11
  · exact p670849_a1_u13
  · exact p670849_a2_u13
  · exact p670849_a3_u13
  · exact p670849_a4_u13
  · exact p670849_a5_u13
  · exact p670849_a6_u13
  · exact p670849_a1_u17
  · exact p670849_a2_u17
  · exact p670849_a3_u17
  · exact p670849_a4_u17
  · exact p670849_a5_u17
  · exact p670849_a6_u17
  · exact p670849_a1_u19
  · exact p670849_a2_u19
  · exact p670849_a3_u19
  · exact p670849_a4_u19
  · exact p670849_a5_u19
  · exact p670849_a6_u19
  · exact p670849_a1_u23
  · exact p670849_a2_u23
  · exact p670849_a3_u23
  · exact p670849_a4_u23
  · exact p670849_a5_u23
  · exact p670849_a6_u23

#print axioms no_witness_670849_box

end OutcastsMathLab.Research.HardPrimes20261005
