"""Generate OutcastsMathLab/Research/HardPrimes20261005.lean.

For each hard prime p and each pair (a, u) of the 53-pair box, factor a*p+u by trial
division, check (independently of the Lean side) that no divisor s has 4au | s+1, and
emit a Lean theorem whose proof is: factorization certificate (checked by `decide`),
primality of each factor (`norm_num`), and the sub-product check (`decide`).
Exact integer arithmetic only; no external libraries."""
import sys
from math import gcd, isqrt

HARD = [345601, 670849]
BOX = [(a, u) for a in range(1, 7) for u in range(1, 7) if gcd(a, u) == 1] + \
      [(a, u) for u in (11, 13, 17, 19, 23) for a in range(1, 7)]

def factor(n):
    f = []; d = 2
    while d * d <= n:
        e = 0
        while n % d == 0: n //= d; e += 1
        if e: f.append((d, e))
        d += 1 if d == 2 else 2
    if n > 1: f.append((n, 1))
    return f

def divisors(n):
    ds = []
    for d in range(1, isqrt(n) + 1):
        if n % d == 0:
            ds.append(d)
            if d * d != n: ds.append(n // d)
    return ds

def lean_list(f):
    return "[" + ", ".join(f"({q}, {e})" for q, e in f) + "]"

out = []
out.append("import OutcastsMathLab.Research.DeterministicFailure\n")
out.append("/-! Generated by `Research/DeterministicFailure/gen_certificates.py`. Do not edit by hand.\n"
           "Finite negative certificates: the two primes below have no Dahan witness at any pair of the\n"
           "53-pair box used in the Outcasts failure atlas. Known criterion, not a new existence result. -/\n")
out.append("namespace OutcastsMathLab.Research.HardPrimes20261005\n")
out.append("open OutcastsMathLab.Research.DeterministicFailure\n")
out.append("/-- The 53 pairs `(a, u)`: coprime `a, u ≤ 6`, and `u ∈ {11, 13, 17, 19, 23}`, `a ≤ 6`. -/")
out.append("def box53 : List (ℕ × ℕ) := " + "[" + ", ".join(f"({a}, {u})" for a, u in BOX) + "]\n")
stats = {}
for p in HARD:
    names = []
    large = set(); maxq = 0
    for a, u in BOX:
        M = a * p + u; m = 4 * a * u
        f = factor(M)
        assert all(q ** e for q, e in f) and eval("*".join(f"{q}**{e}" for q, e in f)) == M
        # independent check of the claim
        assert not any((s + 1) % m == 0 for s in divisors(M)), (p, a, u)
        for q, _ in f:
            if q > 7: large.add(q); maxq = max(maxq, q)
        name = f"p{p}_a{a}_u{u}"
        names.append(name)
        out.append(f"theorem {name} : ∀ s, ¬ DivisorWitness {p} {a} {u} s :=\n"
                   f"  no_divisorWitness_of_cert (L := {lean_list(f)})\n"
                   f"    (by norm_num [List.forall_mem_cons]) (by decide) (by decide)\n")
    out.append(f"/-- `p = {p}` has no Dahan witness at any pair of the 53-pair box. -/")
    out.append(f"theorem no_witness_{p}_box : ∀ au ∈ box53, ∀ s, ¬ DivisorWitness {p} au.1 au.2 s := by")
    out.append("  intro au hau")
    out.append("  simp only [box53, List.mem_cons, List.not_mem_nil, or_false] at hau")
    out.append("  rcases hau with " + " | ".join(["rfl"] * len(BOX)))
    for name in names:
        out.append(f"  · exact {name}")
    out.append("")
    out.append(f"#print axioms no_witness_{p}_box\n")
    stats[p] = (len(large), maxq)
out.append("end OutcastsMathLab.Research.HardPrimes20261005")
open("OutcastsMathLab/Research/HardPrimes20261005.lean", "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("pairs per prime:", len(BOX), "| distinct primes > 7 and max:", stats, file=sys.stderr)
